openapi: 3.0.3
info:
  title: Octagon openAPI
  description: This is Super-Super-Heroes' code platform
  version: 0.0.1
servers:
  - url: http://localhost:8080/
paths:
  /users:
    post:
      tags:
        - users
      summary: Create new user
      description: Create and add a new user to Octagon.
      operationId: addUser
      requestBody:
        required: true
        description: Created user object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Successful create and add user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "default":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    User:
      type: object
      required:
        - id
        - firstname
        - lastname
        - email
        - password
        - createdap
      properties:
        id:
          type: string
          format: uuid
          example: fdd807b4-f6a3-46d6-a583-1aaf09f6f09a
          minLength: 36
          maxLength: 36
        email:
          type: string
          format: email
          uniqueItems: true
          example: john@email.com
        firstName:
          type: string
          minLength: 2
          maxLength: 256
          example: John
        lastName:
          type: string
          minLength: 2
          maxLength: 256
          example: Doe
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 256
          example: "123456Aa"
        createdat:
          type: string
          format: 2022-9-22 23:31:7
          example: 2022-9-22 23:31:7
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          example: 409
        message:
          type: string
          example: User provided email that already exists
