openapi: 3.0.3
info:
  title: Octagon openAPI
  description: This is Super-Super-Heroes' code platform
  version: 0.0.1
servers:
  - url: http://localhost:8080/
paths:
  /users:
    post:
      tags:
         - users
      summary: Creates new user
      description: This endpoint for create and add a new user to Octagon. Request consists of user id, user first name, user last name, user password and created AT. Response may be consist of status code and response message
      requestBody:
        required: true
        description: Created user object
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Successful created and added user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
        '409':
          description: User provided email that already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/409'
        '422':
          description: User is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/422'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500'      
components:
  schemas:
    User:
      type: object
      required:
        - id
        - firstname
        - lastname
        - email
        - password
        - createdap
      properties:
        id:
          type: string
          format: uuid
          example: 	fdd807b4-f6a3-46d6-a583-1aaf09f6f09a
        email:
          description: must be @ and must be unique
          type: string
          format: email
          maxLength: 256
          uniqueItems: true
          example: john@email.com
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        password:
          description: only ASCII symbols 
          type: string
          format: password
          minLength: 8
          maxLength: 256
          example: '123456Aa'
        createdat:
          type: string
          format: 2022-9-22 23:31:7
          example: 2022-9-22 23:31:7
    409:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
    422:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string      
    500:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string  
